### PR TITLE
Serialize issue of Nullable enums/strcuts list with custom JsonFormatter #6

### PR DESCRIPTION
**Pull request by chronoxor**
https://github.com/zcsizmadia/ZCS.Utf8Json/issues/6

### CODE REVIEW

**Comment by zcsizmadia** [comment]
Could you add some unit testing? I wonder how this behaves for different types. E.g. basic types (string, int, ...), structs and classes, DateTime, TimeSpan ....

**Comment by chronoxor** [comment]
Yes, I'll try to provide some more unit tests for the fix. In my [FastBinaryEncoding](https://github.com/chronoxor/FastBinaryEncoding) project I already have json serialization support for primitive types (int, string, decimal, arrays), structs, nullable types, DateTime, Lists, Dictionaries. And with this fix we see the similar behaviour for tree C# Json engines - Utf8Json, System.Text.Json and NewtonSoft.Json.

And Utf8Json shows the best serialize/deserialize performance!

**Comment by zcsizmadia** [comment]
I do love the performance of Utf8Json. I am using it on very low latency and high speed application. The speed (especially the deserialization) is superior to the others.

My only concern is this new feature somehow colliding with the existing Nullable implementations e.g NullableDateTime....

**Comment by chronoxor** [comment]
I've just limited to fallback to `StaticNullableFormatter` only for structs types. This should collide with existing Nullable implementations.

**Comment by chronoxor** [comment]
Add unit test for NullableFormatter with different types (int, int?, string, DateTime, DateTime?, class, struct, struct?, enum, enum?). This test will fail without my fix!

**Comment by zcsizmadia** [comment]
Looks good.
1. Could you add `#nullable enable` around the code which creates CodeQL warnings?
2. What is the formatter precedence if someone created a custom nullable formatter in an already existing code and now the attribute creates abother nullable formatter? I wonder if the custom user defined or the attribute based nullable formatter will be used.

**Comment by chronoxor** [comment]
Just checked if you provide your own custom NullableFormatter it will be used prior to `StaticNullableFormatter`:
image

**Comment by chronoxor** [comment]
#nullable enable was added

**Comment by zcsizmadia** [comment]
@chronoxor Pushed [v1.4.3](https://www.nuget.org/packages/ZCS.Utf8Json) to nuget.org

**Pull request merged**
